import csv

# Additional training data for weak departments
# Covers: Sanitation, Water Supply, Public Health, Waste Management,
#         Drainage, Road Maintenance, Electricity, Public Lighting
# Languages: English, Hindi (Hinglish), Bengali (Banglish)

DATA = [

    # ─── SANITATION (target: 150+ new rows) ───────────────────────────────────
    # English
    ("garbage not collected today", "Sanitation"),
    ("no sweeper came this morning", "Sanitation"),
    ("the street cleaner has not shown up", "Sanitation"),
    ("sanitation worker absent", "Sanitation"),
    ("road sweeping not done", "Sanitation"),
    ("dustbin overflowing on main road", "Sanitation"),
    ("garbage pile near school", "Sanitation"),
    ("waste not picked up for 3 days", "Sanitation"),
    ("open garbage near my house", "Sanitation"),
    ("sanitation team missing", "Sanitation"),
    ("public dustbin not cleaned", "Sanitation"),
    ("foul smell from garbage heap", "Sanitation"),
    ("trash scattered everywhere", "Sanitation"),
    ("no garbage van came today", "Sanitation"),
    ("street is full of litter", "Sanitation"),
    ("garbage bin is broken", "Sanitation"),
    ("waste dumped on footpath", "Sanitation"),
    ("no cleaning in our area for 5 days", "Sanitation"),
    ("the waste collector did not visit", "Sanitation"),
    ("trash piling up outside market", "Sanitation"),
    ("public toilet is very dirty", "Sanitation"),
    ("toilet in park is not clean", "Sanitation"),
    ("community toilet overflowing", "Sanitation"),
    ("no soap or water in public toilet", "Sanitation"),
    ("public bathroom stinking badly", "Sanitation"),
    ("drain cleaner not working", "Sanitation"),
    ("sweeper skipped our lane today", "Sanitation"),
    ("dog waste on footpath not cleaned", "Sanitation"),
    ("dead animal on road not removed", "Sanitation"),
    ("carcass smell near road", "Sanitation"),
    ("garbage truck not arriving on time", "Sanitation"),
    ("waste piled since last week", "Sanitation"),
    ("uncollected garbage attracting flies", "Sanitation"),
    ("rodents due to uncollected waste", "Sanitation"),
    ("rubbish heap near children park", "Sanitation"),
    ("the sweeper did not come for a week", "Sanitation"),
    ("litter bins full and overflowing", "Sanitation"),
    ("nobody collecting garbage in colony", "Sanitation"),
    ("no cleanliness drive in our area", "Sanitation"),
    ("trash stinks near hospital entrance", "Sanitation"),
    ("garbage left on road after festival", "Sanitation"),
    ("waste collection is irregular", "Sanitation"),
    ("waste bin has no lid", "Sanitation"),
    ("cleaning staff not coming", "Sanitation"),
    ("our locality has not been swept today", "Sanitation"),
    # Hindi
    ("safai nahi hui aaj", "Sanitation"),
    ("kachra gaadi nahi aayi", "Sanitation"),
    ("safai karmchari nahi aaya", "Sanitation"),
    ("dustbin bhar gaya hai", "Sanitation"),
    ("nali ki safai nahi hui", "Sanitation"),
    ("raste pe kachra pada hai", "Sanitation"),
    ("mohalley mein safai nahi hui", "Sanitation"),
    ("kachra uthane wala nahi aaya", "Sanitation"),
    ("jhadu nahi laga aaj", "Sanitation"),
    ("ganda paani raste par beh raha hai", "Sanitation"),
    ("kachra phela hua hai poori gali mein", "Sanitation"),
    ("dustbin ka dhakkan toot gaya", "Sanitation"),
    ("sarkari toilet bahut ganda hai", "Sanitation"),
    ("toilet mein paani nahi hai", "Sanitation"),
    ("safai wala hafte bhar se nahi aaya", "Sanitation"),
    ("badbu aa rahi hai kachrे se", "Sanitation"),
    ("moraliy ke paas kachra pada hai", "Sanitation"),
    ("shmashan ke paas kachra", "Sanitation"),
    ("safai na hone se machhar ho rahe hain", "Sanitation"),
    ("kachra jala rahe hain khuli jagah mein", "Sanitation"),
    ("open mein kachra pheka ja raha hai", "Sanitation"),
    ("mara hua janwar sadak par pada hai", "Sanitation"),
    ("market mein safai nahi hoti", "Sanitation"),
    ("dustbin bahut purana aur toot gaya hai", "Sanitation"),
    ("safai vibhag ka number nahi lag raha", "Sanitation"),
    # Bengali
    ("safai hoyni aaj", "Sanitation"),
    ("kachra gaari asheni", "Sanitation"),
    ("safai karmi asheni", "Sanitation"),
    ("dustbin bhorti hoye geche", "Sanitation"),
    ("rasta jharu dewa hoyni aaj", "Sanitation"),
    ("rastay kachra pore ache", "Sanitation"),
    ("elakay safai hoyni", "Sanitation"),
    ("kachra tola hoyni aaj", "Sanitation"),
    ("jharu lagano hoyni", "Sanitation"),
    ("kachra chhorie ache chharidike", "Sanitation"),
    ("dustbin er dhakna nei", "Sanitation"),
    ("sarkari toilet khub nongra", "Sanitation"),
    ("toilet e jol nei", "Sanitation"),
    ("safai kormi ek hapta asheni", "Sanitation"),
    ("baje gondho asche kachra theke", "Sanitation"),
    ("mora kukur rastay pore ache", "Sanitation"),
    ("bajar er kachra tola hoyni", "Sanitation"),
    ("moyla porano hocche khola jaya gaye", "Sanitation"),
    ("kachra jalano theke dhoa", "Sanitation"),
    ("mosha hocche safai na howar jonne", "Sanitation"),

    # ─── WATER SUPPLY (target: 150+ new rows) ─────────────────────────────────
    # English
    ("water has not come since morning", "Water Supply"),
    ("no water supply in our area today", "Water Supply"),
    ("water pressure is very low", "Water Supply"),
    ("tap is completely dry", "Water Supply"),
    ("drinking water not available", "Water Supply"),
    ("water supply has been cut", "Water Supply"),
    ("dirty water coming from tap", "Water Supply"),
    ("muddy water in pipeline", "Water Supply"),
    ("water smells bad", "Water Supply"),
    ("yellowish water from tap", "Water Supply"),
    ("water pipe burst on road", "Water Supply"),
    ("pipeline is leaking", "Water Supply"),
    ("underground pipe broken", "Water Supply"),
    ("water is wasting due to pipe leak", "Water Supply"),
    ("water pump not working", "Water Supply"),
    ("motor pump broken", "Water Supply"),
    ("overhead tank is empty", "Water Supply"),
    ("no water for 2 days", "Water Supply"),
    ("water tanker not arrived", "Water Supply"),
    ("water tanker delayed", "Water Supply"),
    ("community water tap not working", "Water Supply"),
    ("borewell not functioning", "Water Supply"),
    ("handpump is broken", "Water Supply"),
    ("water meter is faulty", "Water Supply"),
    ("got wrong water bill", "Water Supply"),
    ("excess billing for water", "Water Supply"),
    ("water not safe for drinking", "Water Supply"),
    ("RO plant not working in colony", "Water Supply"),
    ("filter in water supply broken", "Water Supply"),
    ("water supply irregular in our area", "Water Supply"),
    ("getting water only for 30 minutes", "Water Supply"),
    ("water supply time changed without notice", "Water Supply"),
    ("the water supply connection is broken", "Water Supply"),
    ("no water at night", "Water Supply"),
    ("no morning water supply", "Water Supply"),
    ("air in water pipeline making noise", "Water Supply"),
    ("water tastes salty", "Water Supply"),
    ("water tastes like chlorine", "Water Supply"),
    ("black particles in water", "Water Supply"),
    ("rust colored water from tap", "Water Supply"),
    ("our tap is always trickling", "Water Supply"),
    ("main water line damaged", "Water Supply"),
    ("water leaking in road", "Water Supply"),
    ("water wasting on road", "Water Supply"),
    ("tanker water is dirty", "Water Supply"),
    ("no water connection in new area", "Water Supply"),
    ("new pipeline not connected yet", "Water Supply"),
    # Hindi
    ("paani nahi aa raha", "Water Supply"),
    ("nal se paani nahi aa raha", "Water Supply"),
    ("paani ki supply band hai", "Water Supply"),
    ("ganda paani aa raha hai", "Water Supply"),
    ("paani mein mitti aa rahi hai", "Water Supply"),
    ("paani mein badbu hai", "Water Supply"),
    ("pipe fata hua hai", "Water Supply"),
    ("paani ki motor kharab hai", "Water Supply"),
    ("tank khali hai paani ka", "Water Supply"),
    ("paani tanker nahi aaya", "Water Supply"),
    ("nal toot gaya hai", "Water Supply"),
    ("paani ka pressure bahut kam hai", "Water Supply"),
    ("2 din se paani nahi hai", "Water Supply"),
    ("subah se paani nahi aaya", "Water Supply"),
    ("paani mein kide hai", "Water Supply"),
    ("yellow paani aa raha hai", "Water Supply"),
    ("paani bahut kam aata hai", "Water Supply"),
    ("paani ka connection kharab hai", "Water Supply"),
    ("nali se paani beh raha hai", "Water Supply"),
    ("pipeline mein leak hai", "Water Supply"),
    ("paani ka bill galat aaya", "Water Supply"),
    ("paani safe nahi peene layak nahi", "Water Supply"),
    ("boring kharab ho gayi hai", "Water Supply"),
    ("haath pump nahi chal raha", "Water Supply"),
    ("paani ki supply sirf 30 minute milti hai", "Water Supply"),
    # Bengali
    ("jol asche na subah theke", "Water Supply"),
    ("nal sukha hoye geche", "Water Supply"),
    ("jol er supply bondho", "Water Supply"),
    ("nongra jol asche", "Water Supply"),
    ("jole mati asche", "Water Supply"),
    ("jole gondho asche", "Water Supply"),
    ("pipe fete geche", "Water Supply"),
    ("motor kharap hoye geche", "Water Supply"),
    ("tank khali hoye geche", "Water Supply"),
    ("tanker asheni", "Water Supply"),
    ("nal bhanga", "Water Supply"),
    ("jol er pressure khub kom", "Water Supply"),
    ("2 din dhore jol nei", "Water Supply"),
    ("subah theke jol asheni", "Water Supply"),
    ("joler pipe leak korche", "Water Supply"),
    ("holo jol asche pipe theke", "Water Supply"),
    ("joler bill vul asche", "Water Supply"),
    ("jol khawar yogyo noy", "Water Supply"),
    ("boring kaj korche na", "Water Supply"),
    ("joler supply matro 30 minute", "Water Supply"),

    # ─── PUBLIC HEALTH (target: 150+ new rows) ────────────────────────────────
    # English
    ("mosquito menace in our area", "Public Health"),
    ("dengue cases rising in locality", "Public Health"),
    ("malaria spreading due to stagnant water", "Public Health"),
    ("fogging not done in our area", "Public Health"),
    ("no anti-mosquito spray this month", "Public Health"),
    ("rats in our neighbourhood", "Public Health"),
    ("cockroach infestation in colony", "Public Health"),
    ("stray dogs biting people", "Public Health"),
    ("stray dog bite reported", "Public Health"),
    ("unhygienic food sold on street", "Public Health"),
    ("expired food being sold", "Public Health"),
    ("flies sitting on open food", "Public Health"),
    ("food vendor not following hygiene", "Public Health"),
    ("dirty water causing illness", "Public Health"),
    ("contaminated water supply", "Public Health"),
    ("open defecation on roadside", "Public Health"),
    ("people urinating on public wall", "Public Health"),
    ("rotting garbage causing disease", "Public Health"),
    ("disease outbreak in our area", "Public Health"),
    ("cholera fear in our locality", "Public Health"),
    ("typhoid spreading in colony", "Public Health"),
    ("dead rats on road", "Public Health"),
    ("dead animals causing smell", "Public Health"),
    ("medical waste dumped on road", "Public Health"),
    ("used syringes found on street", "Public Health"),
    ("hospital waste not disposed properly", "Public Health"),
    ("open drains breeding mosquitoes", "Public Health"),
    ("stagnant water near house causing mosquito", "Public Health"),
    ("mosquito larvae in water tank", "Public Health"),
    ("health hazard due to garbage", "Public Health"),
    ("air pollution from burning garbage", "Public Health"),
    ("smoke from factory affecting health", "Public Health"),
    ("chemical smell from nearby factory", "Public Health"),
    ("skin rashes due to water quality", "Public Health"),
    ("children falling sick from dirty water", "Public Health"),
    ("public toilet not sanitized", "Public Health"),
    ("no handwashing facility at public toilet", "Public Health"),
    ("unhygienic slaughterhouse nearby", "Public Health"),
    ("rotting fish in market", "Public Health"),
    ("stale food at restaurant near us", "Public Health"),
    ("local clinic is in unhygienic state", "Public Health"),
    ("no doctor at health centre", "Public Health"),
    ("medicine stock empty at dispensary", "Public Health"),
    ("health camp not organized this year", "Public Health"),
    ("pest control not done in years", "Public Health"),
    # Hindi
    ("machhar bahut hain is ilake mein", "Public Health"),
    ("dengue ka darr hai", "Public Health"),
    ("gande paani se bimari ho rahi hai", "Public Health"),
    ("kaafi bachchon ko bukhar hai", "Public Health"),
    ("khole mein machharon ka dimak ho gaya", "Public Health"),
    ("chuhe bhar gaye hain", "Public Health"),
    ("sarak par mara hua janwar", "Public Health"),
    ("khule mein shoch ho raha hai", "Public Health"),
    ("fogging nahi hui is mahine", "Public Health"),
    ("dadha paani mein machhar ho rahe hain", "Public Health"),
    ("sarak par khula maas bik raha hai", "Public Health"),
    ("galak khane wale nahi aate hospital", "Public Health"),
    ("medical kachra sadak par pada hai", "Public Health"),
    ("sui seringein sadak par mili", "Public Health"),
    ("chemical gandh aa rahi hai factory se", "Public Health"),
    ("prasad ka rasoi ganda hai mandir ke paas", "Public Health"),
    ("gande paani se dast ho rahe hain", "Public Health"),
    ("market mein machhi bhari hai", "Public Health"),
    ("sada khana thele par bikta hai", "Public Health"),
    ("jhuggi ke paas machhar bahut hai", "Public Health"),
    ("kutta ne kaata bacche ko", "Public Health"),
    ("awara kuttey hamare mohalle mein khatar", "Public Health"),
    ("hamare ghar ke paas nali mein machhar", "Public Health"),
    ("swasthya shivir nahi laga is saal", "Public Health"),
    ("dawai khatam ho gayi dispensary mein", "Public Health"),
    # Bengali
    ("mosha khub beshi amader elakay", "Public Health"),
    ("dengue r bhoy ache", "Public Health"),
    ("nongra joler jonne rog hoye geche", "Public Health"),
    ("bacchara rog bhogte ache", "Public Health"),
    ("jome thaka joley mosha hocche", "Public Health"),
    ("idur bhere geche", "Public Health"),
    ("rastay mora janwar pore ache", "Public Health"),
    ("khola jayaygay hisu korche lokjon", "Public Health"),
    ("fogging hoyni is mas", "Public Health"),
    ("medical kachra rastay", "Public Health"),
    ("khola maas bikri hocche", "Public Health"),
    ("rog choriye porche elakay", "Public Health"),
    ("kharap jol theke dast hocche", "Public Health"),
    ("mora kukur rastay pore ache", "Public Health"),
    ("kukur kamreche ekta bacchake", "Public Health"),
    ("chemical gondho asche factory theke", "Public Health"),
    ("mosha dimer jonno nala block", "Public Health"),
    ("swasthya kendra theke osudh ses", "Public Health"),
    ("swasthya shivir lagano hoyni", "Public Health"),
    ("haater kach te khola machha bikri", "Public Health"),

    # ─── WASTE MANAGEMENT (target: 100+ new rows) ─────────────────────────────
    # English
    ("large waste dump in our locality", "Waste Management"),
    ("no waste segregation being done", "Waste Management"),
    ("wet and dry waste mixed by collector", "Waste Management"),
    ("garbage truck does not come daily", "Waste Management"),
    ("illegal dumping of waste near park", "Waste Management"),
    ("construction debris on road", "Waste Management"),
    ("builder dumped debris on street", "Waste Management"),
    ("e-waste thrown near our colony", "Waste Management"),
    ("old furniture dumped on street", "Waste Management"),
    ("plastic waste clogging drain", "Waste Management"),
    ("plastic bags scattered on road", "Waste Management"),
    ("waste burning causing pollution", "Waste Management"),
    ("smoke from burning garbage", "Waste Management"),
    ("landfill site smell reaching us", "Waste Management"),
    ("garbage dump near our homes", "Waste Management"),
    ("waste pile attracting crows", "Waste Management"),
    ("vultures sitting on waste dump", "Waste Management"),
    ("waste management not done in slums", "Waste Management"),
    ("community dustbin removed not replaced", "Waste Management"),
    ("biomedical waste near dispensary", "Waste Management"),
    ("hazardous waste found on road", "Waste Management"),
    ("paint cans thrown illegally", "Waste Management"),
    ("chemical waste in nala", "Waste Management"),
    ("industrial waste being dumped here", "Waste Management"),
    ("household waste collection stopped", "Waste Management"),
    # Hindi
    ("kachra uthane ka time fix nahi hai", "Waste Management"),
    ("bheja aur sukha kachra ek saath jata hai", "Waste Management"),
    ("construction malba sadak par hai", "Waste Management"),
    ("purana furniture sadak par pada hai", "Waste Management"),
    ("plastic kachra nali mein fase hua hai", "Waste Management"),
    ("kachra jalaane se smoke aa rahi hai", "Waste Management"),
    ("kachra gaadi hafte mein ek baar aati hai", "Waste Management"),
    ("e-waste colony ke bahar pada hai", "Waste Management"),
    ("chemical kachra nadi mein pheka ja raha", "Waste Management"),
    ("factory waste ilake mein dump ho raha", "Waste Management"),
    ("kachrein ka dhera park ke paas hai", "Waste Management"),
    ("kachra nahi utha rahe kai dino se", "Waste Management"),
    ("hospital ka kachra khule mein", "Waste Management"),
    ("kachra container overflow ho gaya", "Waste Management"),
    ("dustbin nahi rahi is area mein", "Waste Management"),
    # Bengali
    ("kachra tola hocche na protidin", "Waste Management"),
    ("bheja shukno moyla ek sathe jacche", "Waste Management"),
    ("construction er malba rastay", "Waste Management"),
    ("purono asbab rastay fela ache", "Waste Management"),
    ("plastic kachra nala bhorti korche", "Waste Management"),
    ("kachra porano theke dhoa", "Waste Management"),
    ("kachra gaari saptahe ekbar ashe", "Waste Management"),
    ("e-waste chhorie ache elakay", "Waste Management"),
    ("chemical moyla nalay fela hocche", "Waste Management"),
    ("factory moyla dump hocche elakay", "Waste Management"),
    ("dustbin nei amader area te", "Waste Management"),
    ("hospital moyla khola jayaygay", "Waste Management"),
    ("container overflow hocche", "Waste Management"),

    # ─── DRAINAGE (target: 100+ new rows) ─────────────────────────────────────
    # English
    ("water logged on road", "Drainage"),
    ("drain blocked with garbage", "Drainage"),
    ("sewer line choked", "Drainage"),
    ("manhole overflowing on road", "Drainage"),
    ("open manhole without cover", "Drainage"),
    ("drain not cleaned in months", "Drainage"),
    ("sewage water flowing on street", "Drainage"),
    ("rainwater not draining", "Drainage"),
    ("water accumulating in basement", "Drainage"),
    ("sewer smell inside house", "Drainage"),
    ("drain water entering homes", "Drainage"),
    ("nala is overflowing", "Drainage"),
    ("nala blocked by plastic bags", "Drainage"),
    ("dead animals blocking drain", "Drainage"),
    ("roots of tree blocking drain", "Drainage"),
    ("flooding due to blocked drain", "Drainage"),
    ("water not draining after rain", "Drainage"),
    ("drainage system not working", "Drainage"),
    ("drain cleaning not done", "Drainage"),
    ("sewage back-flow in toilets", "Drainage"),
    ("septic tank overflow", "Drainage"),
    ("sewage mixing with drinking water", "Drainage"),
    ("manhole cover missing dangerous", "Drainage"),
    ("child fell in open manhole", "Drainage"),
    ("stagnant water near building", "Drainage"),
    # Hindi
    ("nali jam ho gayi hai", "Drainage"),
    ("manhole overflow ho raha hai", "Drainage"),
    ("barish ka paani nahi nikal raha", "Drainage"),
    ("sewer ka ganda paani sadak par", "Drainage"),
    ("nali ki safai nahi hui kaafi dino se", "Drainage"),
    ("gharon mein paani ghus gaya", "Drainage"),
    ("nala plastic se band ho gaya", "Drainage"),
    ("sewage toilet mein ulta aa raha hai", "Drainage"),
    ("septic tank bhar gaya", "Drainage"),
    ("manhole ka dhakna nahi hai", "Drainage"),
    ("khuli nali se accident ka darr hai", "Drainage"),
    ("sadak par barish ka paani jama hai", "Drainage"),
    ("nali se badbu aa rahi hai", "Drainage"),
    ("sewer line mein problem hai", "Drainage"),
    ("colony mein paani bhar gaya", "Drainage"),
    # Bengali
    ("nala jam hoye geche", "Drainage"),
    ("manhole overflow korche", "Drainage"),
    ("bristir jol jacche na", "Drainage"),
    ("sewer er nongra jol rastay", "Drainage"),
    ("nala shafai hoyni", "Drainage"),
    ("ghare jol dhuke geche", "Drainage"),
    ("nala plastic e bhorti", "Drainage"),
    ("sewage toilet e ultiye asche", "Drainage"),
    ("septic tank bhorti hoye geche", "Drainage"),
    ("manhole er dhakna nei bipojjonok", "Drainage"),
    ("rastay jol jome ache", "Drainage"),
    ("nala theke badbu asche", "Drainage"),
    ("sewer e somossa ache", "Drainage"),
    ("elakay jol bhorti hoye geche", "Drainage"),

    # ─── ROAD MAINTENANCE (target: 100+ new rows) ──────────────────────────────
    # English
    ("big pothole on main road", "Road Maintenance"),
    ("road has dangerous cracks", "Road Maintenance"),
    ("road full of potholes after rain", "Road Maintenance"),
    ("road surface broken completely", "Road Maintenance"),
    ("tarmac coming off", "Road Maintenance"),
    ("footpath is broken", "Road Maintenance"),
    ("footpath tiles missing", "Road Maintenance"),
    ("pavement blocked by parked vehicle", "Road Maintenance"),
    ("road divider damaged", "Road Maintenance"),
    ("speed breaker broken", "Road Maintenance"),
    ("road sign fallen down", "Road Maintenance"),
    ("no road marking visible", "Road Maintenance"),
    ("zebra crossing not visible", "Road Maintenance"),
    ("road too narrow after construction", "Road Maintenance"),
    ("bridge is in bad condition", "Road Maintenance"),
    ("flyover surface broken", "Road Maintenance"),
    ("underpass flooded", "Road Maintenance"),
    ("road repair work incomplete", "Road Maintenance"),
    ("newly built road broken again", "Road Maintenance"),
    ("construction material left on road", "Road Maintenance"),
    ("road barricade left unattended", "Road Maintenance"),
    ("road not repaired after pipeline work", "Road Maintenance"),
    ("dangerous hole in road", "Road Maintenance"),
    ("vehicle got damaged due to pothole", "Road Maintenance"),
    ("road slippery due to oil spill", "Road Maintenance"),
    # Hindi
    ("sadak par bahut bade gadde hain", "Road Maintenance"),
    ("sadak buri tarah se toot gayi hai", "Road Maintenance"),
    ("barish ke baad sadak bahut kharab ho gayi", "Road Maintenance"),
    ("footpath bahut toot gaya hai", "Road Maintenance"),
    ("sadak divider damage ho gaya", "Road Maintenance"),
    ("speed breaker toot gaya", "Road Maintenance"),
    ("sadak ka nishan mita gaya hai", "Road Maintenance"),
    ("sadak par construction malba pada hai", "Road Maintenance"),
    ("pul ki halat bahut kharab hai", "Road Maintenance"),
    ("sadak repair kaam adhoora hai", "Road Maintenance"),
    ("nali khodne ke baad sadak sahi nahi ki", "Road Maintenance"),
    ("bhari gadi se sadak dhansi gayi", "Road Maintenance"),
    ("sadak par dangerous gaddha hai", "Road Maintenance"),
    ("meri gaadi ka tyre phoot gaya gadde se", "Road Maintenance"),
    ("sadak saanp ki tarah ghumi hui hai", "Road Maintenance"),
    # Bengali
    ("raste boro gorto ache", "Road Maintenance"),
    ("rasta khub kharap hoye geche", "Road Maintenance"),
    ("bristir pore rasta bhengeche", "Road Maintenance"),
    ("footpath bhengeche", "Road Maintenance"),
    ("road divider bhanga", "Road Maintenance"),
    ("speed breaker bhange geche", "Road Maintenance"),
    ("rastar nishan dekha jaache na", "Road Maintenance"),
    ("construction er malba rastay pore ache", "Road Maintenance"),
    ("bridge er obostha kharap", "Road Maintenance"),
    ("rasta meramot kaam adhurey ache", "Road Maintenance"),
    ("nala khodar pore rasta thik hoyni", "Road Maintenance"),
    ("bipojjonok gorto rastay", "Road Maintenance"),
    ("gortor jonne garir tyre phete geche", "Road Maintenance"),
    ("rasta e tel dhele slippery", "Road Maintenance"),

    # ─── ELECTRICITY (target: 100+ new rows) ──────────────────────────────────
    # English
    ("power cut since morning", "Electricity"),
    ("electricity not restored yet", "Electricity"),
    ("power outage for 6 hours", "Electricity"),
    ("load shedding in our area", "Electricity"),
    ("lights flickering in house", "Electricity"),
    ("electric pole leaning dangerously", "Electricity"),
    ("live wire on the ground", "Electricity"),
    ("bare wire hanging from pole", "Electricity"),
    ("transformer making loud noise", "Electricity"),
    ("transformer smells burnt", "Electricity"),
    ("electricity bill is very high", "Electricity"),
    ("wrong meter reading on bill", "Electricity"),
    ("meter not working", "Electricity"),
    ("electric meter running fast", "Electricity"),
    ("low voltage problem at home", "Electricity"),
    ("high voltage damaging appliances", "Electricity"),
    ("short circuit happened in house", "Electricity"),
    ("electricity spark from switchboard", "Electricity"),
    ("MCB keeps tripping", "Electricity"),
    ("main fuse blown out", "Electricity"),
    ("street light on during daytime", "Electricity"),
    ("got electric shock from tap", "Electricity"),
    ("underground cable damaged", "Electricity"),
    ("single phase electricity supply only", "Electricity"),
    ("three phase not available", "Electricity"),
    # Hindi
    ("bijli nahi hai subah se", "Electricity"),
    ("bijli ab tak wapas nahi aayi", "Electricity"),
    ("6 ghante se bijli cut hai", "Electricity"),
    ("hamare ilake mein load shedding hai", "Electricity"),
    ("ghar ki roshni jhilmila rahi hai", "Electricity"),
    ("bijli ka khamba teda ho gaya hai", "Electricity"),
    ("live taar sadak par hai", "Electricity"),
    ("khula taar khamba se jhool raha hai", "Electricity"),
    ("transformer se awaaz aa rahi hai", "Electricity"),
    ("transformer se dhuan aa raha hai", "Electricity"),
    ("bijli ka bill bahut jyada aaya", "Electricity"),
    ("meter ki reading galat hai", "Electricity"),
    ("meter band hai", "Electricity"),
    ("ghar mein voltage bahut kam hai", "Electricity"),
    ("voltage zyada hone se gadgetein kharab", "Electricity"),
    ("short circuit ho gaya ghar mein", "Electricity"),
    ("switch board se chingari nikal rahi hai", "Electricity"),
    ("MCB baar baar trip kar raha hai", "Electricity"),
    ("main fuse ud gaya", "Electricity"),
    ("bijli ke taar se shock laga", "Electricity"),
    ("underground cable kharab ho gayi", "Electricity"),
    ("sirf single phase bijli aa rahi hai", "Electricity"),
    ("teen phase bijli band hai", "Electricity"),
    ("bijli vibhag ka koi jawab nahi", "Electricity"),
    ("bijli meter tez chal raha hai", "Electricity"),
    # Bengali
    ("subah theke bijli nei", "Electricity"),
    ("current abo tak phire asheni", "Electricity"),
    ("6 ghonta dhore power cut", "Electricity"),
    ("amader elakay load shedding", "Electricity"),
    ("gharer alo jhikmik korche", "Electricity"),
    ("bijli r khamb beke geche", "Electricity"),
    ("jibonto taar matite pore ache", "Electricity"),
    ("khola taar khamb theke jhulche", "Electricity"),
    ("transformer theke awaj asche", "Electricity"),
    ("transformer theke dhoa asche", "Electricity"),
    ("bijlir bill khub beshi", "Electricity"),
    ("meter reading bhul", "Electricity"),
    ("meter bondho ache", "Electricity"),
    ("ghare voltage khub kom", "Electricity"),
    ("beshi voltage er jonne jinishpatra kharap", "Electricity"),
    ("short circuit hoeche ghare", "Electricity"),
    ("switch board theke chingari", "Electricity"),
    ("MCB bar bar trip korche", "Electricity"),
    ("main fuse ure geche", "Electricity"),
    ("bijlir tar theke shock legeche", "Electricity"),
    ("underground cable kharap", "Electricity"),
    ("single phase bijli asche shudhu", "Electricity"),
    ("3 phase nei amader elakay", "Electricity"),

    # ─── PUBLIC LIGHTING (target: 80+ new rows) ────────────────────────────────
    # English
    ("street light not working at night", "Public Lighting"),
    ("lamp post is broken", "Public Lighting"),
    ("multiple street lights not working", "Public Lighting"),
    ("street light glowing in daytime", "Public Lighting"),
    ("street light flickering", "Public Lighting"),
    ("no light near park at night", "Public Lighting"),
    ("road dark and dangerous at night", "Public Lighting"),
    ("light pole leaning", "Public Lighting"),
    ("bulb replacement needed on my street", "Public Lighting"),
    ("traffic signal lights not working", "Public Lighting"),
    ("light out near school at night", "Public Lighting"),
    ("junction has no street lights", "Public Lighting"),
    ("tube light on pole is fused", "Public Lighting"),
    ("LED street light broken", "Public Lighting"),
    ("no light at bus stop", "Public Lighting"),
    ("dark lane causing safety issues", "Public Lighting"),
    ("women feel unsafe due to no lighting", "Public Lighting"),
    ("entire street without lights", "Public Lighting"),
    ("signal lights blinking red continuously", "Public Lighting"),
    ("signal at crossroads not working", "Public Lighting"),
    # Hindi
    ("raat ko street light nahi jalti", "Public Lighting"),
    ("lamp post toot gaya hai", "Public Lighting"),
    ("hamare mohalle mein andhera hai raat ko", "Public Lighting"),
    ("street light din mein bhi jalti rahti hai", "Public Lighting"),
    ("park ke paas koi light nahi hai", "Public Lighting"),
    ("light ka khamba teda ho gaya", "Public Lighting"),
    ("traffic signal raat ko band ho jata hai", "Public Lighting"),
    ("sadak bilkul andheri hai raat ko", "Public Lighting"),
    ("bus stop ke paas koi roshni nahi", "Public Lighting"),
    ("signal baar baar blink kar raha hai", "Public Lighting"),
    ("street light lag hi nahi hai yahan", "Public Lighting"),
    ("LED bulb toot gaya hai khamba par", "Public Lighting"),
    ("junction par koi bhi light nahi", "Public Lighting"),
    ("school ke bahar raat ko andhera", "Public Lighting"),
    ("mahilaon ko raat ko darr lagta hai andhere se", "Public Lighting"),
    # Bengali
    ("ratre street light jolche na", "Public Lighting"),
    ("lamp post bhanga", "Public Lighting"),
    ("amader elakay ratre andhaar", "Public Lighting"),
    ("street light dine o jole ache", "Public Lighting"),
    ("park er pashe kono alo nei ratre", "Public Lighting"),
    ("light er khamb beke geche", "Public Lighting"),
    ("traffic signal ratre bondho hoye jay", "Public Lighting"),
    ("rasta ratre khub andhaar", "Public Lighting"),
    ("bus stop er kache kono alo nei", "Public Lighting"),
    ("signal bar bar blink korche", "Public Lighting"),
    ("street light nei ekhane", "Public Lighting"),
    ("LED bulb bhenge geche khambe", "Public Lighting"),
    ("crossing e kono alo nei", "Public Lighting"),
    ("school er samne ratre andhaar", "Public Lighting"),
    ("mahilara ratre nirapad bodh korchen na", "Public Lighting"),
]

import os

csv_path = "consumer_complaints.csv"

# Count existing rows per department
import pandas as pd
df_existing = pd.read_csv(csv_path)
print("Existing counts:")
print(df_existing['product'].value_counts().to_string())

# Append new data
added = 0
with open(csv_path, "a", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    for text, dept in DATA:
        text = text.strip()
        if text:
            writer.writerow([text, dept])
            added += 1

print(f"\n✅ Added {added} new training rows.")

# Verify new counts
df_new = pd.read_csv(csv_path)
df_new = df_new.dropna(subset=['complaint_text', 'product'])
df_new = df_new[df_new['product'] != 'product']
print(f"\nNew total: {len(df_new)} rows")
print("\nNew counts per department:")
print(df_new['product'].value_counts().to_string())
